import { buttonVariants } from "@/components/ui/button";
import { page_routes } from "@/lib/routes-config";
import { MoveUpRightIcon, TerminalSquareIcon } from "lucide-react";
import Link from "next/link";

export default function Home() {
  return (
    <div className="flex sm:min-h-[87.5vh] min-h-[82vh] flex-col sm:items-center justify-center text-center sm:py-8 py-14">
      <Link
        href="https://youtu.be/E1rkjZkNquI"
        target="_blank"
        className="mb-5 sm:text-lg flex items-center gap-2 underline underline-offset-4 sm:-mt-12"
      >
        Follow along on Youtube Demo{" "}
        <MoveUpRightIcon className="w-4 h-4 font-extrabold" />
      </Link>
      <h1 className="text-[1.80rem] leading-8 sm:px-8 md:leading-[4.5rem] font-bold mb-4 sm:text-6xl text-left sm:text-center">
        Welcome to Tomodachi Pets
      </h1>
      <p className="mb-8 md:text-lg text-base  max-w-[1200px] text-muted-foreground text-left sm:text-center">
      <span className="font-bold text-black">Tomodachi Pets Game</span> lets you draw or prompt custom pets/companions and their accessories, mint them as unique Pet NFT on the <span className="font-bold text-black">Sui network with Move Contract</span>, personalize it with custom accessories generated by <span className="font-bold text-black">AI</span> and bundle them with <span className="font-bold text-black">Walrus</span> onto your digital pets where they and selected assets will orbit around your cursor on any website! — all with full on-chain composability.
      </p>
      <div className="sm:flex sm:flex-row grid grid-cols-2 items-center sm;gap-5 gap-3 mb-8">
        <Link
          href={`/docs${page_routes[0].href}`}
          className={buttonVariants({ className: "px-6", size: "lg" })}
        >
          Get Stared
        </Link>
        <Link
          href="/blog"
          className={buttonVariants({
            variant: "secondary",
            className: "px-6",
            size: "lg",
          })}
        >
          Read Blog
        </Link>
      </div>
      <div className="sm:flex hidden flex-row items-start sm:gap-2 gap-0.5 text-muted-foreground text-md mt-5 -mb-12 max-[800px]:mb-12 font-code sm:text-base text-sm font-medium">
      <div className="flex flex-col md:flex-row gap-4 w-full max-w-lg items-center justify-center">
          <a
            href="https://github.com/sumionochi/tomodachi-digital-pet"
            target="_blank"
            rel="noopener noreferrer"
            className="flex flex-col items-start justify-between p-4 border rounded-xl bg-white dark:bg-muted shadow-sm hover:shadow transition group flex-1 min-h-[110px] w-full"
            style={{ minWidth: 0 }}
          >
            <div className="flex items-center mb-2">
              <img
                src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
                alt="GitHub Logo"
                className="w-7 h-7 mr-2 rounded"
              />
              <div className="font-bold group-hover:underline text-[#859900] text-lg leading-tight">
                Tomodachi Main Page Repo
              </div>
            </div>
            <div className="text-xs text-muted-foreground ml-9">
              Public repository of main site
            </div>
          </a>
          <a
            href="https://github.com/sumionochi/tomodachi-digital-pet-extension"
            target="_blank"
            rel="noopener noreferrer"
            className="flex flex-col items-start justify-between p-4 border rounded-xl bg-white dark:bg-muted shadow-sm hover:shadow transition group flex-1 min-h-[110px] w-full"
            style={{ minWidth: 0 }}
          >
            <div className="flex items-center mb-2">
              <img
                src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
                alt="GitHub Logo"
                className="w-7 h-7 mr-2 rounded"
              />
              <div className="font-bold group-hover:underline text-[#859900] text-lg leading-tight">
                Tomodachi Extension Repo
              </div>
            </div>
            <div className="text-xs text-muted-foreground ml-9">
              Public repository of browser extension
            </div>
          </a>
        </div>
      </div>
    </div>
  );
}
